services:
  app:
    image: breviori_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    env_file:
      - .env
    environment:
      - ENV=${ENV}
      - DOMAIN_URL=${DOMAIN_URL}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/breviori

volumes:
  breviori:
